version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: quiz-app-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: quizapp
    volumes:
      - mongodb_data:/data/db
    networks:
      - quiz-app-network

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: quiz-app-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://mongodb:27017/quizapp
      JWT_SECRET: ${JWT_SECRET}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
    depends_on:
      - mongodb
    networks:
      - quiz-app-network
    volumes:
      - ../backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: quiz-app-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - quiz-app-network

volumes:
  mongodb_data:

networks:
  quiz-app-network:
    driver: bridge